@echo off
echo Setting up Vercel environment variables...
echo https://hmsgfbaelsawpoubclkx.supabase.co | vercel env add NEXT_PUBLIC_SUPABASE_URL
echo eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhtc2dmYmFlbHNhd3BvdWJjbGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxOTM4NjIsImV4cCI6MjA3Mjc2OTg2Mn0.caQsroiQN_NLwUqKhvMhTmzCwppi3Ux-vVX9heR5ers | vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY
echo eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhtc2dmYmFlbHNhd3BvdWJjbGt4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzE5Mzg2MiwiZXhwIjoyMDcyNzY5ODYyfQ.SHoQtDE2VLhc1dN9msH5Vgr_qwygLuKc2bXECWQ83dY | vercel env add SUPABASE_SERVICE_ROLE_KEY
echo Hangout Restaurant | vercel env add NEXT_PUBLIC_RESTAURANT_NAME